Repository Beafowl-Pull/AGIN, pull requests merged in 2023-11, with the labels that each got.

#1 init-project -> main
  .github/workflows/auto-clang-format.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/mirroring.yml
  .gitignore
  CMakeLists.txt
  CMakePresets.json
  Dependencies.cmake
  cmake/CPM.cmake
  cmake/CompilerWarnings.cmake
  cmake/StandardProjectSettings.cmake
  cmake/Utilities.cmake
  src/CMakeLists.txt
  src/main.cpp
Labels: enhancement

#6 CommandHandler -> main
  .clang-format
  .clang-tidy
  src/CMakeLists.txt
  src/CommandHandler/CMakeLists.txt
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/main.cpp
Labels: enhancement

#10 Start Command -> main
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/CommandHandler/Error.hpp
  src/CommandHandler/Values.hpp
  src/main.cpp
Labels: enhancement

#13 BeginCommand -> main
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
Labels: enhancement

#14 11 main class functor
  src/CMakeLists.txt
  src/Main/CMakeLists.txt
  src/Main/Main.cpp
  src/Main/Main.hpp
  src/main.cpp
Labels: enhancement

#16 handleBreakOnBadArguments -> main
  src/CommandHandler/CommandHandler.cpp
Labels: bug

#17 boardCommand -> main
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/Main/Main.hpp
  src/main.cpp
Labels: enhancement

#21 InfoCommand -> main
  src/CMakeLists.txt
  src/CommandHandler/CMakeLists.txt
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/CommandHandler/InfoClass.hpp
  src/Main/CMakeLists.txt
  src/Main/Main.cpp
Labels: enhancement

#23 InfoCommand -> main
  src/CommandHandler/InfoClass.hpp
Labels: bug, enhancement

#22 OptionalCommand -> main
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/CommandHandler/Error.hpp
  src/CommandHandler/InfoClass.hpp
Labels: enhancement

#26 FixCompilationTA -> main
  Makefile
Labels: bug

#25 18 brain class
  pbrain-gomoku-ai
  src/Brain/Brain.cpp
  src/Brain/Brain.hpp
  src/Brain/BrainValues.hpp
  src/Brain/CMakeLists.txt
  src/CMakeLists.txt
  src/CommandHandler/CommandHandler.cpp
  src/CommandHandler/CommandHandler.hpp
  src/CommandHandler/Values.hpp
  src/Main/Main.cpp
Labels: enhancement
